name: counter_bloc_example
description: bloc example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc_concurrency: any
  freezed_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: any
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true
